twilio/twilio-conversations-demo-react

package.json, yarn.lock
This version bump fixes the post-install script issues.
=> chore: Bump @twilio/conversations version

src/components/message/MessageInputField.tsx
=> style: Apply Prettier fixes

src/components/message/MessageView.tsx
=> fix: Fix reaction box appearance after message send

src/components/message/MessageInputField.tsx
=> style: Apply Prettier formatting

README.md
Added the instruction to deploy all functions, which is necessary for the function to be available for requests.
=> Add Deploy All instruction for Function

.gitignore
=> fix: Ignore credential files

src/firebase-support.ts, yarn.lock
Migrate firebase functions to the new modular format.
Drop old compat libraries usage.
=> RTDSDK-3934 firebase migrate compat

package.json, src/components/settings/Settings.tsx, yarn.lock
Added address validations for participant add actions (SMS, WhatsApp, Chat).
=> Add address validations to participant add action

src/components/conversations/ConversationView.tsx
- make convo title and time since last message bolded
- make last sent message lighter font weight
- center allign sent/received icons
- update color/font/text for failed to send message error text
=> Minor style tweaks to conversation list

src/components/modals/addChatMemberModal.tsx, src/components/modals/addSMSParticipantModal.tsx, src/components/modals/addWhatsAppParticipant.tsx, src/components/settings/Settings.tsx
Added save on enter and form close after chat member creation.
=> Added save on enter and form close after chat member creation.

src/components/modals/ActionErrorModal.tsx, src/components/settings/Settings.tsx, src/constants.ts
Improved error displaying logic.
=> RTDSDK-4039-Improved error displaying logic.

src/components/message/MessageList.tsx, src/components/message/MessageStatus.tsx
=> Add delivery receipts support with ChatLog

src/components/conversations/ConversationContainer.tsx, src/components/conversations/ConversationView.tsx, src/components/message/MessageInput.tsx, src/index.tsx, src/styles.ts
=> Use default twilio style. Remove custom font overrides.

src/api.ts, src/components/login/login.tsx, src/styles.ts, yarn.lock
- don't show missing password/username error until user fills out both fields
- handle returned login error correctly, was crashing because error was an object not as tring
https://user-images.githubusercontent.com/3150927/229240560-8db0f743-56b0-4294-a1fc-9056ae2c8571.mov
=> RTDSDK-4071-login-page-tweaks

src/components/conversations/ConversationDetails.tsx, src/components/conversations/ParticipantsView.tsx, src/components/settings/Settings.tsx, src/styles.ts
=> feat: Add Participants Button when there is only 1 participant

README.md
=> Vercel Deploy

.devcontainer/devcontainer.json, .devcontainer/first-run-notice.txt, README.md
This PR enables GitHub Codespaces in this repo. As follow-up, **we should enable prebuilds for main branch**. Otherwise, the initialization takes a lot of time.
=> [RTDSDK-4114] Integrate with GitHub Codespaces

src/api.ts, src/components/AppContainer.tsx, src/components/AppHeader.tsx, src/components/modals/ModalInputField.tsx, src/components/modals/UserProfileModal.tsx, src/constants.ts
Supercedes #108, see there for description.
=> Add user profile

src/components/Avatar.tsx, src/components/AvatarGroup.tsx, src/components/conversations/ParticipantsView.tsx
Supercedes #107, see descriptions there.
=> Add participants avatars bar

src/components/message/MessageMedia.tsx
This pull request addresses an issue where file downloads were inconsistent in the application. Specifically, while image downloads were functioning correctly, there were problems with the download of other file types, such as PDFs.
To resolve this issue, the following changes were implemented:
``onOpen`` function with correct file SID and file type. It's important to set image variable as undefined otherwise the ``if (image)`` bool is ``true`` in ``MessageList.tsx``.
```
{files.map((file) => (
<ChatAttachment
attachmentIcon={
!isMediaLoaded || sending ? (
<Spinner decorative={false} title="Loading" />
) : (
<DownloadIcon decorative />
)
}
key={`${file.filename ?? ""}.index`}
onClick={() => isMediaLoaded && onOpen(file.sid, undefined, file)}
>
<ChatAttachmentLink href="#">
{file?.filename …
```
=> fixed download files not working

src/api.ts, src/components/message/MessageStatus.tsx
Enabled the Delivered Status Icon to indicate successful message delivery and added distinct colors to all status icons. These enhancements improve user experience and the visual appeal of the chat application. 
- [x ] I acknowledge that all my contributions will be made under the project's license.
=> feat: Enabled Delivered Status and added Color

src/components/login/login.tsx
This pull request addresses the issue with the Enter key not being detected on the login screen, which is causing an inconvenience for users trying to sign in. The proposed changes include the implementation of the 'Enter' key press event listener.
- [ x] I acknowledge that all my contributions will be made under the project's license.
=> fix: Fixed Enter key detection in login screen

src/components/AvatarGroup.tsx, src/components/message/MessageList.tsx, src/components/message/MessageMedia.tsx
This PR aims to address key warnings and a memory leak issue. 
- Added unique "key" props to child components in the `AvatarGroup` and `MessageList` components.
- Investigated and addressed a memory leak issue in the `MessageMedia` component.
- [ x] I acknowledge that all my contributions will be made under the project's license.
=> fix: Removing key warnings and memory leak

src/components/message/Reactions.tsx
Refactored and optimized the ReactionsBox component.
- Improved code structure and organization for better maintainability.
- Included tooltip messages for a more user-friendly experience.
- Updated emoji size and Heart is now Read.
- [ x] I acknowledge that all my contributions will be made under the project's license.
=> Updated Reactions Look & Feel

package.json, src/components/conversations/ConversationContainer.tsx, src/components/message/MessageInputField.tsx, src/components/message/MessageList.tsx, src/components/message/MessagesBox.tsx, src/components/message/Reactions.tsx, yarn.lock
**Description:**
This PR enables file drag-and-drop functionality within the Chat window. When a user drags a file over the designated drop zone, the component's background color dynamically changes to offer visual feedback. This functionality leverages the capabilities of the [react-dropzone](https://www.npmjs.com/package/react-dropzone) library.
accepted files:
```
accept: {
"image/*": [".png", ".jpeg", ".jpg", ".gif"],
},
```
- [ x] I acknowledge that all my contributions will be made under the project's license.
=> feat: Drop in Attachments

src/components/modals/ImagePreviewModal.tsx
=> fix: Set focus on button in the message attachment modal

src/branding.tsx, src/components/AppContainer.tsx, src/components/AppHeader.tsx, src/components/conversations/ConversationsList.tsx
**CodeSwarm**
This PR is for addressing this ticket: RTDSDK-4279
Here, we are extracting the branding elements as constants in a separate file so that it becomes easy to change the branding of the app
=> feat(branding): Branding changes & fixing lint errors
